# Copyright (c) 2025 Boston Dynamics AI Institute LLC. All rights reserved.

default_stages: [pre-commit]
default_install_hook_types: [pre-commit, pre-push]

repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.5.3'
  hooks:
    - id: ruff
      args: ['--fix', '--config', 'pyproject.toml']
      exclude: |
        (?x)^(
          scripts/rsl_rl/.*
        )$

- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
    - id: black
      language_version: python3.10
      args: ['--config', 'pyproject.toml']
      verbose: true

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace

- repo: local
  hooks:
    - id: check-copyright
      name: check that all files have the copyright header
      entry: python scripts/check_copyright.py
      language: python
      files: \.(py|sh|bash)$
      types: [text]
