# Copyright (c) 2025 Boston Dynamics AI Institute LLC. All rights reserved.

[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "ReLIC"
author = "Xinghao Zhu"
maintainer = "Xinghao Zhu"
description="Training code for ReLIC."
repository = "https://github.com/bdaiinstitute/relic.git"
keywords = ["Boston Dynamics Spot", "RL", "isaaclab"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "relic"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
